homeassistant:
  whitelist_external_dirs:
    - "/config/snapshots"
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 94
  unit_system: imperial
  time_zone: UTC
  customize: !include customize.yaml

recorder:
  purge_keep_days: 2

frontend:
  javascript_version: latest

climate:
  - platform: zwave

http:
  base_url: http://192.168.1.62:8123

config:

notify:
  - name: Us
    platform: group
    services:
      - service: ios_davids_iphone
      - service: ios_david_conleys_iphone

updater:

discovery:

history:

logbook:

sun:

sensor:
  - platform: zoneminder
    include_archived: false
  - platform: rest
    resource: http://192.168.1.8/zm/api/monitors/alarm/id:2/command:status.json
    usernam: admin
    password: 66map109
    authentication: digest
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "SN1 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "SN1 PIR"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "SN1 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode1"
    name: "SN1 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "SN2 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "SN2 PIR"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "SN2 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode2"
    name: "SN2 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode3"
    name: "SN3 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode3"
    name: "SN3 PIR"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: "bruh/sensornode3"
    name: "SN3 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode3"
    name: "SN3 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode4"
    name: "SN4 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode4"
    name: "SN4 PIR"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: "bruh/sensornode4"
    name: "SN4 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode4"
    name: "SN4 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "bruh/sensornode5"
    name: "SN5 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode5"
    name: "SN5 PIR"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: "bruh/sensornode5"
    name: "SN5 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "bruh/sensornode5"
    name: "SN5 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'
  - platform: template
    sensors:
      emily_home:
        value_template: >-
          {%- if is_state('device_tracker.david_conleys_iphone', "home")
          or is_state('device_tracker.davidcoysiphone', "home")
              -%}
          True
          {%- else -%}
          False
          {%- endif %}
      david_home:
        value_template: >-
          {%- if is_state('device_tracker.davids_iphone', "home")
          or is_state('device_tracker.davidsiphone', "home")
              -%}
          True
          {%- else -%}
          False
          {%- endif %}
      we_home:
        value_template: >-
          {%- if is_state('device_tracker.david_conleys_iphone', "home")
          or is_state('device_tracker.davidcoysiphone', "home")
          or is_state('device_tracker.davidsiphone', "home")
          or is_state('device_tracker.davids_iphone', "home")
              -%}
          True
          {%- else -%}
          False
          {%- endif %}
        entity_id:
          - device_tracker.david_conleys_iphone
          - device_tracker.davidcoysiphone
          - device_tracker.davids_iphone
          - device_tracker.davidsiphone
      master_status_smoke_co_alarm:
        value_template: >-
            {%- if is_state('sensor.master_bedroom_fire_alarm_type', '13') %}
                Idle
            {%- elif is_state('sensor.master_bedroom_fire_alarm_type', '1') %}
                Fire Detected
            {%- elif is_state('sensor.master_bedroom_fire_alarm_type', '2') %}
                Carbon Monoxide Detected
            {%- elif is_state('sensor.master_bedroom_fire_alarm_type', '12') %}
                Alarm Testing
            {% else %}
                Unknown
            {%- endif %}
        friendly_name: 'Master Smoke/CO Alarm'
      mud_room_status_smoke_co_alarm:
        value_template: >-
            {%- if is_state('sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type', '13') %}
                Idle
            {%- elif is_state('sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type', '1') %}
                Fire Detected
            {%- elif is_state('sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type', '2') %}
                Carbon Monoxide Detected
            {%- elif is_state('sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type', '12') %}
                Alarm Testing
            {% else %}
                Unknown
            {%- endif %}
        friendly_name: 'Mud Room Smoke/CO Alarm'
      nursery_status_smoke_co_alarm:
        value_template: >-
            {%- if is_state('sensor.nursery_fire_co_alarm_type', '13') %}
                Idle
            {%- elif is_state('sensor.nursery_fire_co_alarm_type', '1') %}
                Fire Detected
            {%- elif is_state('sensor.nursery_fire_co_alarm_type', '2') %}
                Carbon Monoxide Detected
            {%- elif is_state('sensor.nursery_fire_co_alarm_type', '12') %}
                Alarm Testing
            {% else %}
                Unknown
            {%- endif %}
        friendly_name: 'Nursery Smoke/CO Alarm'
      garage_multi_motion:
        friendly_name: 'Garage Motion'
        value_template: >-
          {%- if is_state('sensor.living_room_multi_alarm_level', '0') -%}
          off
          {%- else -%}
          on
          {%- endif -%}
  - platform: darksky
    api_key: 0a46e964ab6aba053f77e7607ef56bc9
    forecast: 1
    monitored_conditions:
      - temperature
      - apparent_temperature
      - temperature_min
      - temperature_max
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - icon
      - wind_bearing
      - pressure

tts:
  - platform: google

automation: !include_dir_merge_list automations

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x01,0x02,0x03,0x04,0x05,0x0F,0xBF,0x0B,0xAA,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0xFF"

input_boolean:
  alarm_armed:
    name: Armed
    initial: off
    icon: mdi:car
  sleeping:
    name: Sleeping
    initial: off
    icon: mdi:hotel
  boom_boom:
    name: Boom Boom
    initial: off
    icon: mdi:car
  vacation:
    name: Vacation
    initial: off
    icon: mdi:car
  downstairs_media_playing:
    name: Downstairs Media
    initial: off
    icon: mdi:car
  camera_status:
    name: Inside Cameras
    initial: off
    icon: mdi:cctv

binary_sensor:
  - name: 'emily_home_bayesian'
    platform: 'bayesian'
    prior: 0.2
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.david_conleys_iphone'
        prob_given_true: .95
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.davidcoysiphone'
        prob_given_true: 0.75
        platform: 'state'
        to_state: 'home'
  - name: 'david_home_bayesian'
    platform: 'bayesian'
    prior: 0.2
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.davids_iphone'
        prob_given_true: 0.95
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.davidsiphone'
        prob_given_true: 0.75
        platform: 'state'
        to_state: 'home'

shell_command:
  living_turn_off: !secret living_turn_off_url
  living_turn_on: !secret living_turn_on_url
  dining_turn_off: !secret dining_turn_off_url
  dining_turn_on: !secret dining_turn_on_url
  dining_turn_on_right: !secret dining_turn_on_right_url
  restart_zoneminder: !secret restart_zoneminder
  stop_zoneminder: !secret stop_zoneminder

zoneminder:
  host: 192.168.1.8
  path: /zm/
  path_zms: /zm/cgi-bin/nph-zms
  username: admin
  password: 66map109

camera:
  - platform: zoneminder
  - platform: local_file
    file_path: /config/snapshots/doorbell.jpg

script:
  foscam_off:
    sequence:
    - service: shell_command.living_turn_off
    - service: shell_command.dining_turn_off
  foscam_on:
    sequence:
    - service: shell_command.living_turn_on
    - service: shell_command.dining_turn_on
  dining_on_right:
    sequence:
    - service: shell_command.dining_turn_on_right
  sleeping_on:
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.sleeping
  homearm:
    alias: Home Arm
    sequence:
        service: alarm_control_panel.alarm_arm_home
  disarm:
    alias: Disarm
    sequence:
        service: alarm_control_panel.alarm_disarm

zone:
  name: Duke
  latitude: 36.007323
  longitude: -78.937134
  radius: 500
zone 2:
  name: Martin
  latitude: 35.791008
  longitude: -78.771457
  radius: 500
zone 3:
  name: Veritas
  latitude: 35.917110
  longitude: -78.840225
  radius: 500
zone 4:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 500

group:
  home:
    view: yes
    entities:
      - input_number.downstairs_hvac
      - input_number.upstairs_hvac
      - sensor.we_home
      - sun.sun
      - group.motion
      - group.perimeter
      - group.fire
      - device_tracker.david_conleys_iphone
      - device_tracker.davids_iphone
      - input_boolean.alarm_armed
      - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
      - sensor.linear_tbz48_temperature
      - sensor.linear_tbz48_temperature_2
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_access_control
      - alarm_control_panel.partition_1
      - binary_sensor.emily_home
      - binary_sensor.david_home
      - input_boolean.sleeping
      - input_boolean.alarm_armed
      - input_boolean.heat
      - input_boolean.ac
      - input_boolean.vacation
      - input_boolean.downstairs_media_playing
      - script.disarm
      - script.homearm
      - script.dining_on_right
      - script.foscam_off
      - script.foscam_on
      - sensor.downstairs_thermostat_temperature
      - sensor.upstairs_thermostat_temperature
      - automation.arm_alarm_if_we_leave
  sensor_node_1_card:
    name: Master
    entities:
      - sensor.sn1_temperature
      - sensor.sn1_humidity
      - sensor.sn1_pir
      - light.sn1_led
  sensor_node_2_card:
    name: Nursery
    entities:
      - sensor.sn2_temperature
      - sensor.sn2_humidity
      - sensor.sn2_pir
  sensor_node_3_card:
    name: Guest
    entities:
      - sensor.sn3_temperature
      - sensor.sn3_humidity
      - sensor.sn3_pir
  sensor_node_4_card:
    name: Living Room
    entities:
      - sensor.sn4_temperature
      - sensor.sn4_humidity
      - sensor.sn4_pir
  sensor_node_5_card:
    name: Office
    entities:
      - sensor.sn5_temperature
      - sensor.sn5_humidity
      - sensor.sn5_pir

  lights:
    name: Lights
    view: yes
    entities:
      - group.dining_lights
      - group.living_lights
      - group.led_strips
      - group.lights
      - group.master_bedroom_lights
  cameras:
    name: Cameras
    view: yes
    entities:
      - camera.living_room
      - camera.foyer
      - camera.front_door
      - camera.driveway
      - camera.back_door
      - sensor.living_room_status
      - sensor.living_room_events
      - sensor.foyer_status
      - sensor.foyer_events
      - sensor.front_door_status
      - sensor.front_door_events
      - sensor.driveway_status
      - sensor.driveway_events
      - sensor.back_door_status
      - sensor.back_door_events
      - sensor.rest_sensor
  motion:
    name: Motion Sensors
    entities:
      - binary_sensor.garage_motion_sensor
      - binary_sensor.dining_motion_sensor
      - binary_sensor.Sliding_Motion
      - sensor.garage_multi_motion
  living_motion:
    name: Motion Sensors
    entities:
      - binary_sensor.garage_motion_sensor
      - binary_sensor.Sliding_Motion
  perimeter:
    name: Perimeter
    entities:
      - binary_sensor.Windows
      - binary_sensor.Front_Door
      - binary_sensor.sliding_door_sensor
      - binary_sensor.Glassbreak
      - binary_sensor.Main_Fire
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_burglar_15_10
      - binary_sensor.garage_tilt_opener
      - binary_sensor.garage_door_tilt_sensor

      - binary_sensor.window_next_to_sliding_door_sensor
  Fire:
    name: Fire
    entities:
      - sensor.master_status_smoke_co_alarm
      - sensor.mud_room_status_smoke_co_alarm
      - sensor.nursery_status_smoke_co_alarm
  alarm:
    name: Alarm Away
    entities:
      - zwave.garage_motion
      - zwave.ecolink_pir_motion_sensor
      - binary_sensor.Sliding_Motion
      - binary_sensor.Windows
      - binary_sensor.Front_Door
      - zwave.ecolink_doorwindow_sensor
      - binary_sensor.Glassbreak
      - binary_sensor.Main_Fire
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_burglar_15_10
  alarm_stay:
    name: Alarm Stay
    entities:
      - binary_sensor.Sliding_Motion
      - binary_sensor.Windows
      - binary_sensor.Front_Door
      - zwave.ecolink_doorwindow_sensor
      - binary_sensor.Glassbreak
      - binary_sensor.Main_Fire
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_burglar_15_10
  climate:
    name: climate
    view: yes
    entities:
      - climate.upstairs_thermostat_cooling_1
      - climate.downstairs_thermostat_cooling_1
      - climate.upstairs_thermostat_heating_1
      - climate.downstairs_thermostat_heating_1
      - sensor.living_room_multi_temperature
      - sensor.living_room_multi_relative_humidity
      - group.sensor_node_1_card
      - group.sensor_node_2_card
      - group.sensor_node_3_card
      - group.sensor_node_4_card
      - group.sensor_node_5_card
  master:
    name: Master
    view: yes
    entities:
      - light.6001948a4fa2_192168148
      - input_boolean.boom_boom
  dining_lights:
    name: Dining Room Lights
    entities:
      - switch.foyer_light_switch
      - switch.dining_light_switch
      - switch.foyer_lamp
  garage_doors:
    name: Garage Doors
    entities:
      - binary_sensor.garage_tilt_opener
      - binary_sensor.garage_door_tilt_sensor
  living_lights:
    name: Living Room Lights
    entities:
      - switch.living_room_light_switch
      - light.level
      - switch.living_room_lamp
  master_bedroom_lights:
    name: Master Bedroom Lights
    entities:
      - switch.davids_lamp
      - switch.emilys_lamp
  led_strips:
    name: LED Strips
    entities:
      - light.60019439ee75_192168143
      - light.a020a61cfc62_192168141
  bed_led:
    name: Bed LED Strip
      - light.6001948a4fa2_192168148

envisalink:
  host: 192.168.1.60
  panel_type: HONEYWELL
  user_name: user
  password: !secret envisalink_password
  code: !secret envisalink_code
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  zones:
    01:
      name: 'Slider'
      type: 'opening'
    03:
      name: 'Front Door'
      type: 'opening'
    04:
      name: 'Sliding Motion'
      type: 'motion'
    05:
      name: 'Windows'
      type: 'opening'
    09:
      name: 'Glassbreak'
      type: 'sound'
    10:
      name: 'Main Fire'
      type: 'smoke'
  partitions:
    1:
      name: 'Partition 1'

device_tracker:
  - platform: geofency
  - platform: netgear
    host: 192.168.1.38
    username: admin
    password: 200ShelbyexplORE660514
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes
  # - platform: bluetooth_tracker

ios:

light:
  - platform: flux_led
    automatic_add: True
  - platform: mqtt_json
    name: "SN1 LED"
    state_topic: "bruh/sensornode1"
    command_topic: "bruh/sensornode1/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: group
    name: Downstairs LED
    entities:
      - light.60019439ee75_192168143
      - light.a020a61cfc62_192168141
  - platform: group
    name: Bed LED
    entities:
      - light.6001948a4fa2_192168148
switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      emilys_lamp:
        protocol: 1
        pulselength: 178
        code_on: 1070387
        code_off: 1070396
      davids_lamp:
        protocol: 1
        pulselength: 178
        code_on: 1070531
        code_off: 1070540
      foyer_lamp:
        protocol: 1
        pulselength: 178
        code_on: 1070851
        code_off: 1070860
      living_room_lamp:
        protocol: 1
        pulselength: 178
        code_on: 1072387
        code_off: 1072396
      master_outlet_fan:
        protocol: 1
        pulselength: 178
        code_on: 1078531
        code_off: 1078540

media_player:
  - platform: spotify
    client_id: e9adf7c19d064a47836e67191e5f10b1
    client_secret: 50e1a1a6e5f240c5a9a91e0266e0f5c5

hassio:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.62:3218

mqtt:
  broker: core-mosquitto
  username: admin
  password: 66map109

cloud:
